In [ ]:
import tkinter as tk

In [ ]:
import logging
import threading

import sys
import pandas as pd
import sklearn
import keras

Using TensorFlow backend.

In [ ]:
class TextHandler(logging.Handler):
    """This class allows you to log to a Tkinter Text or ScrolledText widget"""
    def __init__(self, text):
        # run the regular Handler __init__
        logging.Handler.__init__(self)
        # Store a reference to the Text it will log to
        self.text = text

In [ ]:
def emit(self, record):
        msg = self.format(record)
        def append():
            self.text.configure(state='normal')
            self.text.insert(END, msg + '\n')
            self.text.configure(state='disabled')
            # Autoscroll to the bottom
            self.text.yview(END)
        # This is necessary because we can't modify the Text from other threads
        self.text.after(0, append)

In [ ]:
class Autoresized_Notebook(Notebook):
  def __init__(self, master=None, **kw):

    Notebook.__init__(self, master, **kw)
    self.bind("<<NotebookTabChanged>>", self._on_tab_changed)

  def _on_tab_changed(self,event):
    event.widget.update_idletasks()

    tab = event.widget.nametowidget(event.widget.select())
    #event.widget.configure(height=tab.winfo_reqheight())

if __name__== "__main__":
    from Tkinter import Frame, Tk

    # region autism tool
    def run(path):

        # switch to report view
        notebook.select(tab2)

        # Childhood Autistic Spectrum Disorder Screening using Machine Learning
        print('Python: {}'.format(sys.version))
        print('Pandas: {}'.format(pd.__version__))
        print('Sklearn: {}'.format(sklearn.__version__))
        print('Keras: {}'.format(keras.__version__))

NameError: ignored

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Autism-Child-Datasets.csv to Autism-Child-Datasets.csv

In [ ]:
import io
import pandas as pd
df2 = pd.read_csv(io.BytesIO(uploaded['Autism-Child-Datasets.csv']))
# Dataset is now stored in a Pandas Dataframe

In [ ]:
    df2.loc[:10]

    A1_Score  A2_Score  A3_Score  A4_Score  ...  result      age_desc  relation  class
0          1         1         0         0  ...       5  '4-11 years'    Parent     NO
1          1         1         0         0  ...       5  '4-11 years'    Parent     NO
2          1         1         0         0  ...       5  '4-11 years'         ?     NO
3          0         1         0         0  ...       4  '4-11 years'         ?     NO
4          1         1         1         1  ...      10  '4-11 years'    Parent    YES
5          0         0         1         0  ...       5  '4-11 years'         ?     NO
6          1         0         1         1  ...       7  '4-11 years'    Parent    YES
7          1         1         1         1  ...       8  '4-11 years'    Parent    YES
8          1         1         1         1  ...       7  '4-11 years'    Parent    YES
9          0         0         1         1  ...       5  '4-11 years'         ?     NO
10         1         0         0         0  ...       7  '4-11 years'      Self    YES

[11 rows x 21 columns]

In [ ]:
df2.describe()

         A1_Score    A2_Score    A3_Score  ...    A9_Score   A10_Score      result
count  292.000000  292.000000  292.000000  ...  292.000000  292.000000  292.000000
mean     0.633562    0.534247    0.743151  ...    0.493151    0.726027    6.239726
std      0.482658    0.499682    0.437646  ...    0.500811    0.446761    2.284882
min      0.000000    0.000000    0.000000  ...    0.000000    0.000000    0.000000
25%      0.000000    0.000000    0.000000  ...    0.000000    0.000000    5.000000
50%      1.000000    1.000000    1.000000  ...    0.000000    1.000000    6.000000
75%      1.000000    1.000000    1.000000  ...    1.000000    1.000000    8.000000
max      1.000000    1.000000    1.000000  ...    1.000000    1.000000   10.000000

[8 rows x 11 columns]

In [ ]:
df2 = df2.drop(['result', 'age_desc'], axis=1)

df2.loc[:10]

        # create X and Y datasets for training
x = df2.drop(['class'], 1)
y = df2['class']

x.loc[:10]

    A1_Score  A2_Score  A3_Score  ...     contry_of_res  used_app_before  relation
0          1         1         0  ...            Jordan               no    Parent
1          1         1         0  ...            Jordan               no    Parent
2          1         1         0  ...            Jordan              yes         ?
3          0         1         0  ...            Jordan               no         ?
4          1         1         1  ...   'United States'               no    Parent
5          0         0         1  ...             Egypt               no         ?
6          1         0         1  ...  'United Kingdom'               no    Parent
7          1         1         1  ...           Bahrain               no    Parent
8          1         1         1  ...           Bahrain               no    Parent
9          0         0         1  ...           Austria               no         ?
10         1         0         0  ...  'United Kingdom'               no      Self

[11 rows x 18 columns]

In [ ]:
X = pd.get_dummies(x)

        # print the new categorical column labels
X.columns.values

        # print an example patient from the categorical data
X.loc[0]

        # convert the class data to categorical values - one-hot-encoded vectors
Y = pd.get_dummies(y)

Y.iloc[:10]

   NO  YES
0   1    0
1   1    0
2   1    0
3   1    0
4   0    1
5   1    0
6   0    1
7   0    1
8   0    1
9   1    0

In [ ]:
from sklearn import model_selection
        # split the X and Y data into training and testing datasets
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.2)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(233, 96)
(59, 96)
(233, 2)
(59, 2)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

Using TensorFlow backend.

In [ ]:
      def create_model():
            # create model
            model = Sequential()
            model.add(Dense(8, input_dim=96, kernel_initializer='normal', activation='relu'))
            model.add(Dense(4, kernel_initializer='normal', activation='relu'))
            model.add(Dense(2, activation='sigmoid'))

            # compile model
            adam = Adam(lr=0.001)
            model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
            return model

model = create_model()

print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 8)                 776
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 36
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 10
=================================================================
Total params: 822
Trainable params: 822
Non-trainable params: 0
_________________________________________________________________
None

In [ ]:
# fit the model to the training data
model.fit(X_train, Y_train, epochs=50, batch_size=10, verbose=1)

Epoch 1/50
233/233 [==============================] - 0s 1ms/step - loss: 0.6923 - accuracy: 0.5279
Epoch 2/50
233/233 [==============================] - 0s 162us/step - loss: 0.6874 - accuracy: 0.6180
Epoch 3/50
233/233 [==============================] - 0s 159us/step - loss: 0.6798 - accuracy: 0.5966
Epoch 4/50
233/233 [==============================] - 0s 162us/step - loss: 0.6677 - accuracy: 0.5494
Epoch 5/50
233/233 [==============================] - 0s 153us/step - loss: 0.6499 - accuracy: 0.5923
Epoch 6/50
233/233 [==============================] - 0s 177us/step - loss: 0.6278 - accuracy: 0.5751
Epoch 7/50
233/233 [==============================] - 0s 149us/step - loss: 0.5995 - accuracy: 0.6266
Epoch 8/50
233/233 [==============================] - 0s 148us/step - loss: 0.5700 - accuracy: 0.6867
Epoch 9/50
233/233 [==============================] - 0s 178us/step - loss: 0.5393 - accuracy: 0.7682
Epoch 10/50
233/233 [==============================] - 0s 158us/step - loss: 0.5010 - accuracy: 0.7940
Epoch 11/50
233/233 [==============================] - 0s 151us/step - loss: 0.4632 - accuracy: 0.8412
Epoch 12/50
233/233 [==============================] - 0s 155us/step - loss: 0.4255 - accuracy: 0.8798
Epoch 13/50
233/233 [==============================] - 0s 151us/step - loss: 0.3860 - accuracy: 0.9056
Epoch 14/50
233/233 [==============================] - 0s 158us/step - loss: 0.3514 - accuracy: 0.9356
Epoch 15/50
233/233 [==============================] - 0s 132us/step - loss: 0.3136 - accuracy: 0.9399
Epoch 16/50
233/233 [==============================] - 0s 133us/step - loss: 0.2826 - accuracy: 0.9485
Epoch 17/50
233/233 [==============================] - 0s 140us/step - loss: 0.2523 - accuracy: 0.9571
Epoch 18/50
233/233 [==============================] - 0s 133us/step - loss: 0.2252 - accuracy: 0.9528
Epoch 19/50
233/233 [==============================] - 0s 136us/step - loss: 0.1994 - accuracy: 0.9657
Epoch 20/50
233/233 [==============================] - 0s 130us/step - loss: 0.1778 - accuracy: 0.9785
Epoch 21/50
233/233 [==============================] - 0s 140us/step - loss: 0.1590 - accuracy: 0.9742
Epoch 22/50
233/233 [==============================] - 0s 144us/step - loss: 0.1537 - accuracy: 0.9785
Epoch 23/50
233/233 [==============================] - 0s 136us/step - loss: 0.1288 - accuracy: 0.9914
Epoch 24/50
233/233 [==============================] - 0s 169us/step - loss: 0.1230 - accuracy: 0.9785
Epoch 25/50
233/233 [==============================] - 0s 129us/step - loss: 0.1093 - accuracy: 0.9871
Epoch 26/50
233/233 [==============================] - 0s 130us/step - loss: 0.0968 - accuracy: 0.9914
Epoch 27/50
233/233 [==============================] - 0s 129us/step - loss: 0.0897 - accuracy: 0.9914
Epoch 28/50
233/233 [==============================] - 0s 152us/step - loss: 0.0822 - accuracy: 0.9914
Epoch 29/50
233/233 [==============================] - 0s 129us/step - loss: 0.0756 - accuracy: 0.9957
Epoch 30/50
233/233 [==============================] - 0s 139us/step - loss: 0.0724 - accuracy: 0.9914
Epoch 31/50
233/233 [==============================] - 0s 155us/step - loss: 0.0665 - accuracy: 0.9957
Epoch 32/50
233/233 [==============================] - 0s 128us/step - loss: 0.0600 - accuracy: 0.9957
Epoch 33/50
233/233 [==============================] - 0s 133us/step - loss: 0.0556 - accuracy: 0.9957
Epoch 34/50
233/233 [==============================] - 0s 151us/step - loss: 0.0534 - accuracy: 0.9957
Epoch 35/50
233/233 [==============================] - 0s 150us/step - loss: 0.0504 - accuracy: 0.9957
Epoch 36/50
233/233 [==============================] - 0s 126us/step - loss: 0.0464 - accuracy: 0.9957
Epoch 37/50
233/233 [==============================] - 0s 121us/step - loss: 0.0438 - accuracy: 0.9957
Epoch 38/50
233/233 [==============================] - 0s 165us/step - loss: 0.0410 - accuracy: 1.0000
Epoch 39/50
233/233 [==============================] - 0s 124us/step - loss: 0.0400 - accuracy: 0.9957
Epoch 40/50
233/233 [==============================] - 0s 140us/step - loss: 0.0367 - accuracy: 0.9957
Epoch 41/50
233/233 [==============================] - 0s 138us/step - loss: 0.0351 - accuracy: 1.0000
Epoch 42/50
233/233 [==============================] - 0s 135us/step - loss: 0.0342 - accuracy: 0.9957
Epoch 43/50
233/233 [==============================] - 0s 141us/step - loss: 0.0307 - accuracy: 0.9957
Epoch 44/50
233/233 [==============================] - 0s 155us/step - loss: 0.0295 - accuracy: 0.9957
Epoch 45/50
233/233 [==============================] - 0s 139us/step - loss: 0.0295 - accuracy: 0.9957
Epoch 46/50
233/233 [==============================] - 0s 150us/step - loss: 0.0285 - accuracy: 1.0000
Epoch 47/50
233/233 [==============================] - 0s 137us/step - loss: 0.0270 - accuracy: 1.0000
Epoch 48/50
233/233 [==============================] - 0s 135us/step - loss: 0.0265 - accuracy: 1.0000
Epoch 49/50
233/233 [==============================] - 0s 128us/step - loss: 0.0243 - accuracy: 1.0000
Epoch 50/50
233/233 [==============================] - 0s 135us/step - loss: 0.0233 - accuracy: 1.0000

In [ ]:
from sklearn.metrics import classification_report, accuracy_score

predictions = model.predict_classes(X_test)
predictions

print('Results for Categorical Model')
print(accuracy_score(Y_test[['YES']], predictions))
print(classification_report(Y_test[['YES']], predictions))

Results for Categorical Model
0.9661016949152542
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        31
           1       0.93      1.00      0.97        28

    accuracy                           0.97        59
   macro avg       0.97      0.97      0.97        59
weighted avg       0.97      0.97      0.97        59

In [ ]:
with open("report.txt", "a") as f:
            # clear the file
            open('report.txt', 'w').close()
            # write the file
            f.write(str('Shape of DataFrame: {}'.format(df2.shape))
                    + "\n" + str(df2.loc[0])
                    + "\n" + str(X_train.shape)
                    + "\n" + str(X_test.shape)
                    + "\n" + str(Y_train.shape)
                    + "\n" + str(Y_test.shape)
                    + "\n" + "\n" + str(model.summary())
                    + "\n" + "\n" + 'Predictions (0=OK, 1=ASD)'
                    + "\n" + str(predictions)
                    + "\n" + "\n" + 'Results for Categorical Model'
                    + "\n" + str(accuracy_score(Y_test[['YES']], predictions))
                    + "\n" + str(classification_report(Y_test[['YES']], predictions))
                    )

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 8)                 776
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 36
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 10
=================================================================
Total params: 822
Trainable params: 822
Non-trainable params: 0
_________________________________________________________________

In [ ]:
import logging
import threading
logging.warn(str('Shape of DataFrame: {}'.format(df2.shape))
                     + "\n" + str(df2.loc[1])
                     + "\n" + "\n" + 'Test-Train split:'
                     + "\n" + str(X_train.shape)
                     + "\n" + str(X_test.shape)
                     + "\n" + str(Y_train.shape)
                     + "\n" + str(Y_test.shape)
                     + "\n" + "\n" + 'Model Summary:'
                     + "\n" + str(model.summary())
                     + "\n" + "\n" + 'Predictions (0=OK, 1=ASD)'
                     + "\n" + str(predictions)
                     + "\n" + "\n" + 'Results for Categorical Model'
                     + "\n" + str(accuracy_score(Y_test[['YES']], predictions))
                     + "\n" + "\n" + str(classification_report(Y_test[['YES']], predictions)))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  app.launch_new_instance()
WARNING:root:Shape of DataFrame: (292, 19)
A1_Score                           1
A2_Score                           1
A3_Score                           0
A4_Score                           0
A5_Score                           1
A6_Score                           1
A7_Score                           0
A8_Score                           1
A9_Score                           0
A10_Score                          0
age                                6
gender                             m
ethnicity          'Middle Eastern '
jundice                           no
austim                            no
contry_of_res                 Jordan
used_app_before                   no
relation                      Parent
class                             NO
Name: 1, dtype: object

Test-Train split:
(233, 96)
(59, 96)
(233, 2)
(59, 2)

Model Summary:
None

Predictions (0=OK, 1=ASD)
[0 0 1 0 0 1 1 1 1 1 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 1
 1 1 1 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 1]

Results for Categorical Model
0.9661016949152542

              precision    recall  f1-score   support

           0       1.00      0.94      0.97        31
           1       0.93      1.00      0.97        28

    accuracy                           0.97        59
   macro avg       0.97      0.97      0.97        59
weighted avg       0.97      0.97      0.97        59

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 8)                 776
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 36
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 10
=================================================================
Total params: 822
Trainable params: 822
Non-trainable params: 0
_________________________________________________________________